site_name: Saviynt Community Connectors
site_url: https://saviynt.com/
docs_dir: src
theme: readthedocs
markdown_extensions:
    - attr_list
nav:
- 'Home': index.md
- 'Connectors':
    - 'RingCentral': 'ringcentral/index.md'
    - 'Signal Sciences': signalsciences/index.md'